//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExemploMaterializacao.ServicoExposto {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PacienteTO", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class PacienteTO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NomeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NomeMaeField;
        
        private System.Nullable<System.DateTime> NascimentoField;
        
        private ExemploMaterializacao.ServicoExposto.SexoEnum SexoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Nome {
            get {
                return this.NomeField;
            }
            set {
                if ((object.ReferenceEquals(this.NomeField, value) != true)) {
                    this.NomeField = value;
                    this.RaisePropertyChanged("Nome");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string NomeMae {
            get {
                return this.NomeMaeField;
            }
            set {
                if ((object.ReferenceEquals(this.NomeMaeField, value) != true)) {
                    this.NomeMaeField = value;
                    this.RaisePropertyChanged("NomeMae");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public System.Nullable<System.DateTime> Nascimento {
            get {
                return this.NascimentoField;
            }
            set {
                if ((this.NascimentoField.Equals(value) != true)) {
                    this.NascimentoField = value;
                    this.RaisePropertyChanged("Nascimento");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        public ExemploMaterializacao.ServicoExposto.SexoEnum Sexo {
            get {
                return this.SexoField;
            }
            set {
                if ((this.SexoField.Equals(value) != true)) {
                    this.SexoField = value;
                    this.RaisePropertyChanged("Sexo");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SexoEnum", Namespace="http://tempuri.org/")]
    public enum SexoEnum : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Masculino = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Feminino = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        NaoInformado = 2,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CarroTO", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class CarroTO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ModeloField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AnoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MarcaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PlacaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CorField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Modelo {
            get {
                return this.ModeloField;
            }
            set {
                if ((object.ReferenceEquals(this.ModeloField, value) != true)) {
                    this.ModeloField = value;
                    this.RaisePropertyChanged("Modelo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Ano {
            get {
                return this.AnoField;
            }
            set {
                if ((object.ReferenceEquals(this.AnoField, value) != true)) {
                    this.AnoField = value;
                    this.RaisePropertyChanged("Ano");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string Marca {
            get {
                return this.MarcaField;
            }
            set {
                if ((object.ReferenceEquals(this.MarcaField, value) != true)) {
                    this.MarcaField = value;
                    this.RaisePropertyChanged("Marca");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string Placa {
            get {
                return this.PlacaField;
            }
            set {
                if ((object.ReferenceEquals(this.PlacaField, value) != true)) {
                    this.PlacaField = value;
                    this.RaisePropertyChanged("Placa");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string Cor {
            get {
                return this.CorField;
            }
            set {
                if ((object.ReferenceEquals(this.CorField, value) != true)) {
                    this.CorField = value;
                    this.RaisePropertyChanged("Cor");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UsuarioTO", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class UsuarioTO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NomeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NomeUsuarioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SenhaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ConfirmarSenhaField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Nome {
            get {
                return this.NomeField;
            }
            set {
                if ((object.ReferenceEquals(this.NomeField, value) != true)) {
                    this.NomeField = value;
                    this.RaisePropertyChanged("Nome");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string NomeUsuario {
            get {
                return this.NomeUsuarioField;
            }
            set {
                if ((object.ReferenceEquals(this.NomeUsuarioField, value) != true)) {
                    this.NomeUsuarioField = value;
                    this.RaisePropertyChanged("NomeUsuario");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string Email {
            get {
                return this.EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailField, value) != true)) {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string Senha {
            get {
                return this.SenhaField;
            }
            set {
                if ((object.ReferenceEquals(this.SenhaField, value) != true)) {
                    this.SenhaField = value;
                    this.RaisePropertyChanged("Senha");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string ConfirmarSenha {
            get {
                return this.ConfirmarSenhaField;
            }
            set {
                if ((object.ReferenceEquals(this.ConfirmarSenhaField, value) != true)) {
                    this.ConfirmarSenhaField = value;
                    this.RaisePropertyChanged("ConfirmarSenha");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServicoExposto.ServicoSoap")]
    public interface ServicoSoap {
        
        // CODEGEN: Gerando contrato de mensagem porque o nome do elemento GetMeusPacientesResult no namespace http://tempuri.org/ não está marcado como nulo
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetMeusPacientes", ReplyAction="*")]
        ExemploMaterializacao.ServicoExposto.GetMeusPacientesResponse GetMeusPacientes(ExemploMaterializacao.ServicoExposto.GetMeusPacientesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetMeusPacientes", ReplyAction="*")]
        System.Threading.Tasks.Task<ExemploMaterializacao.ServicoExposto.GetMeusPacientesResponse> GetMeusPacientesAsync(ExemploMaterializacao.ServicoExposto.GetMeusPacientesRequest request);
        
        // CODEGEN: Gerando contrato de mensagem porque o nome do elemento GetPacientePorIdResult no namespace http://tempuri.org/ não está marcado como nulo
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetPacientePorId", ReplyAction="*")]
        ExemploMaterializacao.ServicoExposto.GetPacientePorIdResponse GetPacientePorId(ExemploMaterializacao.ServicoExposto.GetPacientePorIdRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetPacientePorId", ReplyAction="*")]
        System.Threading.Tasks.Task<ExemploMaterializacao.ServicoExposto.GetPacientePorIdResponse> GetPacientePorIdAsync(ExemploMaterializacao.ServicoExposto.GetPacientePorIdRequest request);
        
        // CODEGEN: Gerando contrato de mensagem porque o nome do elemento pacienteTO no namespace http://tempuri.org/ não está marcado como nulo
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AdicionarPaciente", ReplyAction="*")]
        ExemploMaterializacao.ServicoExposto.AdicionarPacienteResponse AdicionarPaciente(ExemploMaterializacao.ServicoExposto.AdicionarPacienteRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AdicionarPaciente", ReplyAction="*")]
        System.Threading.Tasks.Task<ExemploMaterializacao.ServicoExposto.AdicionarPacienteResponse> AdicionarPacienteAsync(ExemploMaterializacao.ServicoExposto.AdicionarPacienteRequest request);
        
        // CODEGEN: Gerando contrato de mensagem porque o nome do elemento pacienteTO no namespace http://tempuri.org/ não está marcado como nulo
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AtualizarPaciente", ReplyAction="*")]
        ExemploMaterializacao.ServicoExposto.AtualizarPacienteResponse AtualizarPaciente(ExemploMaterializacao.ServicoExposto.AtualizarPacienteRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AtualizarPaciente", ReplyAction="*")]
        System.Threading.Tasks.Task<ExemploMaterializacao.ServicoExposto.AtualizarPacienteResponse> AtualizarPacienteAsync(ExemploMaterializacao.ServicoExposto.AtualizarPacienteRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ExcluirPaciente", ReplyAction="*")]
        void ExcluirPaciente(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ExcluirPaciente", ReplyAction="*")]
        System.Threading.Tasks.Task ExcluirPacienteAsync(int id);
        
        // CODEGEN: Gerando contrato de mensagem porque o nome do elemento GetTodosCarrosResult no namespace http://tempuri.org/ não está marcado como nulo
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetTodosCarros", ReplyAction="*")]
        ExemploMaterializacao.ServicoExposto.GetTodosCarrosResponse GetTodosCarros(ExemploMaterializacao.ServicoExposto.GetTodosCarrosRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetTodosCarros", ReplyAction="*")]
        System.Threading.Tasks.Task<ExemploMaterializacao.ServicoExposto.GetTodosCarrosResponse> GetTodosCarrosAsync(ExemploMaterializacao.ServicoExposto.GetTodosCarrosRequest request);
        
        // CODEGEN: Gerando contrato de mensagem porque o nome do elemento GetCarroPorIdResult no namespace http://tempuri.org/ não está marcado como nulo
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetCarroPorId", ReplyAction="*")]
        ExemploMaterializacao.ServicoExposto.GetCarroPorIdResponse GetCarroPorId(ExemploMaterializacao.ServicoExposto.GetCarroPorIdRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetCarroPorId", ReplyAction="*")]
        System.Threading.Tasks.Task<ExemploMaterializacao.ServicoExposto.GetCarroPorIdResponse> GetCarroPorIdAsync(ExemploMaterializacao.ServicoExposto.GetCarroPorIdRequest request);
        
        // CODEGEN: Gerando contrato de mensagem porque o nome do elemento carroTO no namespace http://tempuri.org/ não está marcado como nulo
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AdicionarCarro", ReplyAction="*")]
        ExemploMaterializacao.ServicoExposto.AdicionarCarroResponse AdicionarCarro(ExemploMaterializacao.ServicoExposto.AdicionarCarroRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AdicionarCarro", ReplyAction="*")]
        System.Threading.Tasks.Task<ExemploMaterializacao.ServicoExposto.AdicionarCarroResponse> AdicionarCarroAsync(ExemploMaterializacao.ServicoExposto.AdicionarCarroRequest request);
        
        // CODEGEN: Gerando contrato de mensagem porque o nome do elemento carroTO no namespace http://tempuri.org/ não está marcado como nulo
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AtualizarCarro", ReplyAction="*")]
        ExemploMaterializacao.ServicoExposto.AtualizarCarroResponse AtualizarCarro(ExemploMaterializacao.ServicoExposto.AtualizarCarroRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AtualizarCarro", ReplyAction="*")]
        System.Threading.Tasks.Task<ExemploMaterializacao.ServicoExposto.AtualizarCarroResponse> AtualizarCarroAsync(ExemploMaterializacao.ServicoExposto.AtualizarCarroRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ExcluirCarro", ReplyAction="*")]
        void ExcluirCarro(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ExcluirCarro", ReplyAction="*")]
        System.Threading.Tasks.Task ExcluirCarroAsync(int id);
        
        // CODEGEN: Gerando contrato de mensagem porque o nome do elemento usuarioTO no namespace http://tempuri.org/ não está marcado como nulo
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/RegistrarUsuario", ReplyAction="*")]
        ExemploMaterializacao.ServicoExposto.RegistrarUsuarioResponse RegistrarUsuario(ExemploMaterializacao.ServicoExposto.RegistrarUsuarioRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/RegistrarUsuario", ReplyAction="*")]
        System.Threading.Tasks.Task<ExemploMaterializacao.ServicoExposto.RegistrarUsuarioResponse> RegistrarUsuarioAsync(ExemploMaterializacao.ServicoExposto.RegistrarUsuarioRequest request);
        
        // CODEGEN: Gerando contrato de mensagem porque o nome do elemento nomeUsuario no namespace http://tempuri.org/ não está marcado como nulo
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/LoginUsuario", ReplyAction="*")]
        ExemploMaterializacao.ServicoExposto.LoginUsuarioResponse LoginUsuario(ExemploMaterializacao.ServicoExposto.LoginUsuarioRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/LoginUsuario", ReplyAction="*")]
        System.Threading.Tasks.Task<ExemploMaterializacao.ServicoExposto.LoginUsuarioResponse> LoginUsuarioAsync(ExemploMaterializacao.ServicoExposto.LoginUsuarioRequest request);
        
        // CODEGEN: Gerando contrato de mensagem porque o nome do elemento nomeUsuario no namespace http://tempuri.org/ não está marcado como nulo
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetPerfilUsuario", ReplyAction="*")]
        ExemploMaterializacao.ServicoExposto.GetPerfilUsuarioResponse GetPerfilUsuario(ExemploMaterializacao.ServicoExposto.GetPerfilUsuarioRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetPerfilUsuario", ReplyAction="*")]
        System.Threading.Tasks.Task<ExemploMaterializacao.ServicoExposto.GetPerfilUsuarioResponse> GetPerfilUsuarioAsync(ExemploMaterializacao.ServicoExposto.GetPerfilUsuarioRequest request);
        
        // CODEGEN: Gerando contrato de mensagem porque o nome do elemento usuarioTO no namespace http://tempuri.org/ não está marcado como nulo
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AtualizarPerfilUsuario", ReplyAction="*")]
        ExemploMaterializacao.ServicoExposto.AtualizarPerfilUsuarioResponse AtualizarPerfilUsuario(ExemploMaterializacao.ServicoExposto.AtualizarPerfilUsuarioRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AtualizarPerfilUsuario", ReplyAction="*")]
        System.Threading.Tasks.Task<ExemploMaterializacao.ServicoExposto.AtualizarPerfilUsuarioResponse> AtualizarPerfilUsuarioAsync(ExemploMaterializacao.ServicoExposto.AtualizarPerfilUsuarioRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetMeusPacientesRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetMeusPacientes", Namespace="http://tempuri.org/", Order=0)]
        public ExemploMaterializacao.ServicoExposto.GetMeusPacientesRequestBody Body;
        
        public GetMeusPacientesRequest() {
        }
        
        public GetMeusPacientesRequest(ExemploMaterializacao.ServicoExposto.GetMeusPacientesRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetMeusPacientesRequestBody {
        
        public GetMeusPacientesRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetMeusPacientesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetMeusPacientesResponse", Namespace="http://tempuri.org/", Order=0)]
        public ExemploMaterializacao.ServicoExposto.GetMeusPacientesResponseBody Body;
        
        public GetMeusPacientesResponse() {
        }
        
        public GetMeusPacientesResponse(ExemploMaterializacao.ServicoExposto.GetMeusPacientesResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetMeusPacientesResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ExemploMaterializacao.ServicoExposto.PacienteTO[] GetMeusPacientesResult;
        
        public GetMeusPacientesResponseBody() {
        }
        
        public GetMeusPacientesResponseBody(ExemploMaterializacao.ServicoExposto.PacienteTO[] GetMeusPacientesResult) {
            this.GetMeusPacientesResult = GetMeusPacientesResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetPacientePorIdRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetPacientePorId", Namespace="http://tempuri.org/", Order=0)]
        public ExemploMaterializacao.ServicoExposto.GetPacientePorIdRequestBody Body;
        
        public GetPacientePorIdRequest() {
        }
        
        public GetPacientePorIdRequest(ExemploMaterializacao.ServicoExposto.GetPacientePorIdRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetPacientePorIdRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int id;
        
        public GetPacientePorIdRequestBody() {
        }
        
        public GetPacientePorIdRequestBody(int id) {
            this.id = id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetPacientePorIdResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetPacientePorIdResponse", Namespace="http://tempuri.org/", Order=0)]
        public ExemploMaterializacao.ServicoExposto.GetPacientePorIdResponseBody Body;
        
        public GetPacientePorIdResponse() {
        }
        
        public GetPacientePorIdResponse(ExemploMaterializacao.ServicoExposto.GetPacientePorIdResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetPacientePorIdResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ExemploMaterializacao.ServicoExposto.PacienteTO GetPacientePorIdResult;
        
        public GetPacientePorIdResponseBody() {
        }
        
        public GetPacientePorIdResponseBody(ExemploMaterializacao.ServicoExposto.PacienteTO GetPacientePorIdResult) {
            this.GetPacientePorIdResult = GetPacientePorIdResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AdicionarPacienteRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AdicionarPaciente", Namespace="http://tempuri.org/", Order=0)]
        public ExemploMaterializacao.ServicoExposto.AdicionarPacienteRequestBody Body;
        
        public AdicionarPacienteRequest() {
        }
        
        public AdicionarPacienteRequest(ExemploMaterializacao.ServicoExposto.AdicionarPacienteRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AdicionarPacienteRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ExemploMaterializacao.ServicoExposto.PacienteTO pacienteTO;
        
        public AdicionarPacienteRequestBody() {
        }
        
        public AdicionarPacienteRequestBody(ExemploMaterializacao.ServicoExposto.PacienteTO pacienteTO) {
            this.pacienteTO = pacienteTO;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AdicionarPacienteResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AdicionarPacienteResponse", Namespace="http://tempuri.org/", Order=0)]
        public ExemploMaterializacao.ServicoExposto.AdicionarPacienteResponseBody Body;
        
        public AdicionarPacienteResponse() {
        }
        
        public AdicionarPacienteResponse(ExemploMaterializacao.ServicoExposto.AdicionarPacienteResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class AdicionarPacienteResponseBody {
        
        public AdicionarPacienteResponseBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AtualizarPacienteRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AtualizarPaciente", Namespace="http://tempuri.org/", Order=0)]
        public ExemploMaterializacao.ServicoExposto.AtualizarPacienteRequestBody Body;
        
        public AtualizarPacienteRequest() {
        }
        
        public AtualizarPacienteRequest(ExemploMaterializacao.ServicoExposto.AtualizarPacienteRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AtualizarPacienteRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ExemploMaterializacao.ServicoExposto.PacienteTO pacienteTO;
        
        public AtualizarPacienteRequestBody() {
        }
        
        public AtualizarPacienteRequestBody(ExemploMaterializacao.ServicoExposto.PacienteTO pacienteTO) {
            this.pacienteTO = pacienteTO;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AtualizarPacienteResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AtualizarPacienteResponse", Namespace="http://tempuri.org/", Order=0)]
        public ExemploMaterializacao.ServicoExposto.AtualizarPacienteResponseBody Body;
        
        public AtualizarPacienteResponse() {
        }
        
        public AtualizarPacienteResponse(ExemploMaterializacao.ServicoExposto.AtualizarPacienteResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class AtualizarPacienteResponseBody {
        
        public AtualizarPacienteResponseBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetTodosCarrosRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetTodosCarros", Namespace="http://tempuri.org/", Order=0)]
        public ExemploMaterializacao.ServicoExposto.GetTodosCarrosRequestBody Body;
        
        public GetTodosCarrosRequest() {
        }
        
        public GetTodosCarrosRequest(ExemploMaterializacao.ServicoExposto.GetTodosCarrosRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetTodosCarrosRequestBody {
        
        public GetTodosCarrosRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetTodosCarrosResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetTodosCarrosResponse", Namespace="http://tempuri.org/", Order=0)]
        public ExemploMaterializacao.ServicoExposto.GetTodosCarrosResponseBody Body;
        
        public GetTodosCarrosResponse() {
        }
        
        public GetTodosCarrosResponse(ExemploMaterializacao.ServicoExposto.GetTodosCarrosResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetTodosCarrosResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ExemploMaterializacao.ServicoExposto.CarroTO[] GetTodosCarrosResult;
        
        public GetTodosCarrosResponseBody() {
        }
        
        public GetTodosCarrosResponseBody(ExemploMaterializacao.ServicoExposto.CarroTO[] GetTodosCarrosResult) {
            this.GetTodosCarrosResult = GetTodosCarrosResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetCarroPorIdRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetCarroPorId", Namespace="http://tempuri.org/", Order=0)]
        public ExemploMaterializacao.ServicoExposto.GetCarroPorIdRequestBody Body;
        
        public GetCarroPorIdRequest() {
        }
        
        public GetCarroPorIdRequest(ExemploMaterializacao.ServicoExposto.GetCarroPorIdRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetCarroPorIdRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int id;
        
        public GetCarroPorIdRequestBody() {
        }
        
        public GetCarroPorIdRequestBody(int id) {
            this.id = id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetCarroPorIdResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetCarroPorIdResponse", Namespace="http://tempuri.org/", Order=0)]
        public ExemploMaterializacao.ServicoExposto.GetCarroPorIdResponseBody Body;
        
        public GetCarroPorIdResponse() {
        }
        
        public GetCarroPorIdResponse(ExemploMaterializacao.ServicoExposto.GetCarroPorIdResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetCarroPorIdResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ExemploMaterializacao.ServicoExposto.CarroTO GetCarroPorIdResult;
        
        public GetCarroPorIdResponseBody() {
        }
        
        public GetCarroPorIdResponseBody(ExemploMaterializacao.ServicoExposto.CarroTO GetCarroPorIdResult) {
            this.GetCarroPorIdResult = GetCarroPorIdResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AdicionarCarroRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AdicionarCarro", Namespace="http://tempuri.org/", Order=0)]
        public ExemploMaterializacao.ServicoExposto.AdicionarCarroRequestBody Body;
        
        public AdicionarCarroRequest() {
        }
        
        public AdicionarCarroRequest(ExemploMaterializacao.ServicoExposto.AdicionarCarroRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AdicionarCarroRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ExemploMaterializacao.ServicoExposto.CarroTO carroTO;
        
        public AdicionarCarroRequestBody() {
        }
        
        public AdicionarCarroRequestBody(ExemploMaterializacao.ServicoExposto.CarroTO carroTO) {
            this.carroTO = carroTO;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AdicionarCarroResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AdicionarCarroResponse", Namespace="http://tempuri.org/", Order=0)]
        public ExemploMaterializacao.ServicoExposto.AdicionarCarroResponseBody Body;
        
        public AdicionarCarroResponse() {
        }
        
        public AdicionarCarroResponse(ExemploMaterializacao.ServicoExposto.AdicionarCarroResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class AdicionarCarroResponseBody {
        
        public AdicionarCarroResponseBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AtualizarCarroRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AtualizarCarro", Namespace="http://tempuri.org/", Order=0)]
        public ExemploMaterializacao.ServicoExposto.AtualizarCarroRequestBody Body;
        
        public AtualizarCarroRequest() {
        }
        
        public AtualizarCarroRequest(ExemploMaterializacao.ServicoExposto.AtualizarCarroRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AtualizarCarroRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ExemploMaterializacao.ServicoExposto.CarroTO carroTO;
        
        public AtualizarCarroRequestBody() {
        }
        
        public AtualizarCarroRequestBody(ExemploMaterializacao.ServicoExposto.CarroTO carroTO) {
            this.carroTO = carroTO;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AtualizarCarroResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AtualizarCarroResponse", Namespace="http://tempuri.org/", Order=0)]
        public ExemploMaterializacao.ServicoExposto.AtualizarCarroResponseBody Body;
        
        public AtualizarCarroResponse() {
        }
        
        public AtualizarCarroResponse(ExemploMaterializacao.ServicoExposto.AtualizarCarroResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class AtualizarCarroResponseBody {
        
        public AtualizarCarroResponseBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RegistrarUsuarioRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="RegistrarUsuario", Namespace="http://tempuri.org/", Order=0)]
        public ExemploMaterializacao.ServicoExposto.RegistrarUsuarioRequestBody Body;
        
        public RegistrarUsuarioRequest() {
        }
        
        public RegistrarUsuarioRequest(ExemploMaterializacao.ServicoExposto.RegistrarUsuarioRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class RegistrarUsuarioRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ExemploMaterializacao.ServicoExposto.UsuarioTO usuarioTO;
        
        public RegistrarUsuarioRequestBody() {
        }
        
        public RegistrarUsuarioRequestBody(ExemploMaterializacao.ServicoExposto.UsuarioTO usuarioTO) {
            this.usuarioTO = usuarioTO;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RegistrarUsuarioResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="RegistrarUsuarioResponse", Namespace="http://tempuri.org/", Order=0)]
        public ExemploMaterializacao.ServicoExposto.RegistrarUsuarioResponseBody Body;
        
        public RegistrarUsuarioResponse() {
        }
        
        public RegistrarUsuarioResponse(ExemploMaterializacao.ServicoExposto.RegistrarUsuarioResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class RegistrarUsuarioResponseBody {
        
        public RegistrarUsuarioResponseBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class LoginUsuarioRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="LoginUsuario", Namespace="http://tempuri.org/", Order=0)]
        public ExemploMaterializacao.ServicoExposto.LoginUsuarioRequestBody Body;
        
        public LoginUsuarioRequest() {
        }
        
        public LoginUsuarioRequest(ExemploMaterializacao.ServicoExposto.LoginUsuarioRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class LoginUsuarioRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string nomeUsuario;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string senha;
        
        public LoginUsuarioRequestBody() {
        }
        
        public LoginUsuarioRequestBody(string nomeUsuario, string senha) {
            this.nomeUsuario = nomeUsuario;
            this.senha = senha;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class LoginUsuarioResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="LoginUsuarioResponse", Namespace="http://tempuri.org/", Order=0)]
        public ExemploMaterializacao.ServicoExposto.LoginUsuarioResponseBody Body;
        
        public LoginUsuarioResponse() {
        }
        
        public LoginUsuarioResponse(ExemploMaterializacao.ServicoExposto.LoginUsuarioResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class LoginUsuarioResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ExemploMaterializacao.ServicoExposto.UsuarioTO LoginUsuarioResult;
        
        public LoginUsuarioResponseBody() {
        }
        
        public LoginUsuarioResponseBody(ExemploMaterializacao.ServicoExposto.UsuarioTO LoginUsuarioResult) {
            this.LoginUsuarioResult = LoginUsuarioResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetPerfilUsuarioRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetPerfilUsuario", Namespace="http://tempuri.org/", Order=0)]
        public ExemploMaterializacao.ServicoExposto.GetPerfilUsuarioRequestBody Body;
        
        public GetPerfilUsuarioRequest() {
        }
        
        public GetPerfilUsuarioRequest(ExemploMaterializacao.ServicoExposto.GetPerfilUsuarioRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetPerfilUsuarioRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string nomeUsuario;
        
        public GetPerfilUsuarioRequestBody() {
        }
        
        public GetPerfilUsuarioRequestBody(string nomeUsuario) {
            this.nomeUsuario = nomeUsuario;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetPerfilUsuarioResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetPerfilUsuarioResponse", Namespace="http://tempuri.org/", Order=0)]
        public ExemploMaterializacao.ServicoExposto.GetPerfilUsuarioResponseBody Body;
        
        public GetPerfilUsuarioResponse() {
        }
        
        public GetPerfilUsuarioResponse(ExemploMaterializacao.ServicoExposto.GetPerfilUsuarioResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetPerfilUsuarioResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ExemploMaterializacao.ServicoExposto.UsuarioTO GetPerfilUsuarioResult;
        
        public GetPerfilUsuarioResponseBody() {
        }
        
        public GetPerfilUsuarioResponseBody(ExemploMaterializacao.ServicoExposto.UsuarioTO GetPerfilUsuarioResult) {
            this.GetPerfilUsuarioResult = GetPerfilUsuarioResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AtualizarPerfilUsuarioRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AtualizarPerfilUsuario", Namespace="http://tempuri.org/", Order=0)]
        public ExemploMaterializacao.ServicoExposto.AtualizarPerfilUsuarioRequestBody Body;
        
        public AtualizarPerfilUsuarioRequest() {
        }
        
        public AtualizarPerfilUsuarioRequest(ExemploMaterializacao.ServicoExposto.AtualizarPerfilUsuarioRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AtualizarPerfilUsuarioRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ExemploMaterializacao.ServicoExposto.UsuarioTO usuarioTO;
        
        public AtualizarPerfilUsuarioRequestBody() {
        }
        
        public AtualizarPerfilUsuarioRequestBody(ExemploMaterializacao.ServicoExposto.UsuarioTO usuarioTO) {
            this.usuarioTO = usuarioTO;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AtualizarPerfilUsuarioResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AtualizarPerfilUsuarioResponse", Namespace="http://tempuri.org/", Order=0)]
        public ExemploMaterializacao.ServicoExposto.AtualizarPerfilUsuarioResponseBody Body;
        
        public AtualizarPerfilUsuarioResponse() {
        }
        
        public AtualizarPerfilUsuarioResponse(ExemploMaterializacao.ServicoExposto.AtualizarPerfilUsuarioResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class AtualizarPerfilUsuarioResponseBody {
        
        public AtualizarPerfilUsuarioResponseBody() {
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ServicoSoapChannel : ExemploMaterializacao.ServicoExposto.ServicoSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServicoSoapClient : System.ServiceModel.ClientBase<ExemploMaterializacao.ServicoExposto.ServicoSoap>, ExemploMaterializacao.ServicoExposto.ServicoSoap {
        
        public ServicoSoapClient() {
        }
        
        public ServicoSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServicoSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicoSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicoSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ExemploMaterializacao.ServicoExposto.GetMeusPacientesResponse ExemploMaterializacao.ServicoExposto.ServicoSoap.GetMeusPacientes(ExemploMaterializacao.ServicoExposto.GetMeusPacientesRequest request) {
            return base.Channel.GetMeusPacientes(request);
        }
        
        public ExemploMaterializacao.ServicoExposto.PacienteTO[] GetMeusPacientes() {
            ExemploMaterializacao.ServicoExposto.GetMeusPacientesRequest inValue = new ExemploMaterializacao.ServicoExposto.GetMeusPacientesRequest();
            inValue.Body = new ExemploMaterializacao.ServicoExposto.GetMeusPacientesRequestBody();
            ExemploMaterializacao.ServicoExposto.GetMeusPacientesResponse retVal = ((ExemploMaterializacao.ServicoExposto.ServicoSoap)(this)).GetMeusPacientes(inValue);
            return retVal.Body.GetMeusPacientesResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ExemploMaterializacao.ServicoExposto.GetMeusPacientesResponse> ExemploMaterializacao.ServicoExposto.ServicoSoap.GetMeusPacientesAsync(ExemploMaterializacao.ServicoExposto.GetMeusPacientesRequest request) {
            return base.Channel.GetMeusPacientesAsync(request);
        }
        
        public System.Threading.Tasks.Task<ExemploMaterializacao.ServicoExposto.GetMeusPacientesResponse> GetMeusPacientesAsync() {
            ExemploMaterializacao.ServicoExposto.GetMeusPacientesRequest inValue = new ExemploMaterializacao.ServicoExposto.GetMeusPacientesRequest();
            inValue.Body = new ExemploMaterializacao.ServicoExposto.GetMeusPacientesRequestBody();
            return ((ExemploMaterializacao.ServicoExposto.ServicoSoap)(this)).GetMeusPacientesAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ExemploMaterializacao.ServicoExposto.GetPacientePorIdResponse ExemploMaterializacao.ServicoExposto.ServicoSoap.GetPacientePorId(ExemploMaterializacao.ServicoExposto.GetPacientePorIdRequest request) {
            return base.Channel.GetPacientePorId(request);
        }
        
        public ExemploMaterializacao.ServicoExposto.PacienteTO GetPacientePorId(int id) {
            ExemploMaterializacao.ServicoExposto.GetPacientePorIdRequest inValue = new ExemploMaterializacao.ServicoExposto.GetPacientePorIdRequest();
            inValue.Body = new ExemploMaterializacao.ServicoExposto.GetPacientePorIdRequestBody();
            inValue.Body.id = id;
            ExemploMaterializacao.ServicoExposto.GetPacientePorIdResponse retVal = ((ExemploMaterializacao.ServicoExposto.ServicoSoap)(this)).GetPacientePorId(inValue);
            return retVal.Body.GetPacientePorIdResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ExemploMaterializacao.ServicoExposto.GetPacientePorIdResponse> ExemploMaterializacao.ServicoExposto.ServicoSoap.GetPacientePorIdAsync(ExemploMaterializacao.ServicoExposto.GetPacientePorIdRequest request) {
            return base.Channel.GetPacientePorIdAsync(request);
        }
        
        public System.Threading.Tasks.Task<ExemploMaterializacao.ServicoExposto.GetPacientePorIdResponse> GetPacientePorIdAsync(int id) {
            ExemploMaterializacao.ServicoExposto.GetPacientePorIdRequest inValue = new ExemploMaterializacao.ServicoExposto.GetPacientePorIdRequest();
            inValue.Body = new ExemploMaterializacao.ServicoExposto.GetPacientePorIdRequestBody();
            inValue.Body.id = id;
            return ((ExemploMaterializacao.ServicoExposto.ServicoSoap)(this)).GetPacientePorIdAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ExemploMaterializacao.ServicoExposto.AdicionarPacienteResponse ExemploMaterializacao.ServicoExposto.ServicoSoap.AdicionarPaciente(ExemploMaterializacao.ServicoExposto.AdicionarPacienteRequest request) {
            return base.Channel.AdicionarPaciente(request);
        }
        
        public void AdicionarPaciente(ExemploMaterializacao.ServicoExposto.PacienteTO pacienteTO) {
            ExemploMaterializacao.ServicoExposto.AdicionarPacienteRequest inValue = new ExemploMaterializacao.ServicoExposto.AdicionarPacienteRequest();
            inValue.Body = new ExemploMaterializacao.ServicoExposto.AdicionarPacienteRequestBody();
            inValue.Body.pacienteTO = pacienteTO;
            ExemploMaterializacao.ServicoExposto.AdicionarPacienteResponse retVal = ((ExemploMaterializacao.ServicoExposto.ServicoSoap)(this)).AdicionarPaciente(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ExemploMaterializacao.ServicoExposto.AdicionarPacienteResponse> ExemploMaterializacao.ServicoExposto.ServicoSoap.AdicionarPacienteAsync(ExemploMaterializacao.ServicoExposto.AdicionarPacienteRequest request) {
            return base.Channel.AdicionarPacienteAsync(request);
        }
        
        public System.Threading.Tasks.Task<ExemploMaterializacao.ServicoExposto.AdicionarPacienteResponse> AdicionarPacienteAsync(ExemploMaterializacao.ServicoExposto.PacienteTO pacienteTO) {
            ExemploMaterializacao.ServicoExposto.AdicionarPacienteRequest inValue = new ExemploMaterializacao.ServicoExposto.AdicionarPacienteRequest();
            inValue.Body = new ExemploMaterializacao.ServicoExposto.AdicionarPacienteRequestBody();
            inValue.Body.pacienteTO = pacienteTO;
            return ((ExemploMaterializacao.ServicoExposto.ServicoSoap)(this)).AdicionarPacienteAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ExemploMaterializacao.ServicoExposto.AtualizarPacienteResponse ExemploMaterializacao.ServicoExposto.ServicoSoap.AtualizarPaciente(ExemploMaterializacao.ServicoExposto.AtualizarPacienteRequest request) {
            return base.Channel.AtualizarPaciente(request);
        }
        
        public void AtualizarPaciente(ExemploMaterializacao.ServicoExposto.PacienteTO pacienteTO) {
            ExemploMaterializacao.ServicoExposto.AtualizarPacienteRequest inValue = new ExemploMaterializacao.ServicoExposto.AtualizarPacienteRequest();
            inValue.Body = new ExemploMaterializacao.ServicoExposto.AtualizarPacienteRequestBody();
            inValue.Body.pacienteTO = pacienteTO;
            ExemploMaterializacao.ServicoExposto.AtualizarPacienteResponse retVal = ((ExemploMaterializacao.ServicoExposto.ServicoSoap)(this)).AtualizarPaciente(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ExemploMaterializacao.ServicoExposto.AtualizarPacienteResponse> ExemploMaterializacao.ServicoExposto.ServicoSoap.AtualizarPacienteAsync(ExemploMaterializacao.ServicoExposto.AtualizarPacienteRequest request) {
            return base.Channel.AtualizarPacienteAsync(request);
        }
        
        public System.Threading.Tasks.Task<ExemploMaterializacao.ServicoExposto.AtualizarPacienteResponse> AtualizarPacienteAsync(ExemploMaterializacao.ServicoExposto.PacienteTO pacienteTO) {
            ExemploMaterializacao.ServicoExposto.AtualizarPacienteRequest inValue = new ExemploMaterializacao.ServicoExposto.AtualizarPacienteRequest();
            inValue.Body = new ExemploMaterializacao.ServicoExposto.AtualizarPacienteRequestBody();
            inValue.Body.pacienteTO = pacienteTO;
            return ((ExemploMaterializacao.ServicoExposto.ServicoSoap)(this)).AtualizarPacienteAsync(inValue);
        }
        
        public void ExcluirPaciente(int id) {
            base.Channel.ExcluirPaciente(id);
        }
        
        public System.Threading.Tasks.Task ExcluirPacienteAsync(int id) {
            return base.Channel.ExcluirPacienteAsync(id);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ExemploMaterializacao.ServicoExposto.GetTodosCarrosResponse ExemploMaterializacao.ServicoExposto.ServicoSoap.GetTodosCarros(ExemploMaterializacao.ServicoExposto.GetTodosCarrosRequest request) {
            return base.Channel.GetTodosCarros(request);
        }
        
        public ExemploMaterializacao.ServicoExposto.CarroTO[] GetTodosCarros() {
            ExemploMaterializacao.ServicoExposto.GetTodosCarrosRequest inValue = new ExemploMaterializacao.ServicoExposto.GetTodosCarrosRequest();
            inValue.Body = new ExemploMaterializacao.ServicoExposto.GetTodosCarrosRequestBody();
            ExemploMaterializacao.ServicoExposto.GetTodosCarrosResponse retVal = ((ExemploMaterializacao.ServicoExposto.ServicoSoap)(this)).GetTodosCarros(inValue);
            return retVal.Body.GetTodosCarrosResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ExemploMaterializacao.ServicoExposto.GetTodosCarrosResponse> ExemploMaterializacao.ServicoExposto.ServicoSoap.GetTodosCarrosAsync(ExemploMaterializacao.ServicoExposto.GetTodosCarrosRequest request) {
            return base.Channel.GetTodosCarrosAsync(request);
        }
        
        public System.Threading.Tasks.Task<ExemploMaterializacao.ServicoExposto.GetTodosCarrosResponse> GetTodosCarrosAsync() {
            ExemploMaterializacao.ServicoExposto.GetTodosCarrosRequest inValue = new ExemploMaterializacao.ServicoExposto.GetTodosCarrosRequest();
            inValue.Body = new ExemploMaterializacao.ServicoExposto.GetTodosCarrosRequestBody();
            return ((ExemploMaterializacao.ServicoExposto.ServicoSoap)(this)).GetTodosCarrosAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ExemploMaterializacao.ServicoExposto.GetCarroPorIdResponse ExemploMaterializacao.ServicoExposto.ServicoSoap.GetCarroPorId(ExemploMaterializacao.ServicoExposto.GetCarroPorIdRequest request) {
            return base.Channel.GetCarroPorId(request);
        }
        
        public ExemploMaterializacao.ServicoExposto.CarroTO GetCarroPorId(int id) {
            ExemploMaterializacao.ServicoExposto.GetCarroPorIdRequest inValue = new ExemploMaterializacao.ServicoExposto.GetCarroPorIdRequest();
            inValue.Body = new ExemploMaterializacao.ServicoExposto.GetCarroPorIdRequestBody();
            inValue.Body.id = id;
            ExemploMaterializacao.ServicoExposto.GetCarroPorIdResponse retVal = ((ExemploMaterializacao.ServicoExposto.ServicoSoap)(this)).GetCarroPorId(inValue);
            return retVal.Body.GetCarroPorIdResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ExemploMaterializacao.ServicoExposto.GetCarroPorIdResponse> ExemploMaterializacao.ServicoExposto.ServicoSoap.GetCarroPorIdAsync(ExemploMaterializacao.ServicoExposto.GetCarroPorIdRequest request) {
            return base.Channel.GetCarroPorIdAsync(request);
        }
        
        public System.Threading.Tasks.Task<ExemploMaterializacao.ServicoExposto.GetCarroPorIdResponse> GetCarroPorIdAsync(int id) {
            ExemploMaterializacao.ServicoExposto.GetCarroPorIdRequest inValue = new ExemploMaterializacao.ServicoExposto.GetCarroPorIdRequest();
            inValue.Body = new ExemploMaterializacao.ServicoExposto.GetCarroPorIdRequestBody();
            inValue.Body.id = id;
            return ((ExemploMaterializacao.ServicoExposto.ServicoSoap)(this)).GetCarroPorIdAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ExemploMaterializacao.ServicoExposto.AdicionarCarroResponse ExemploMaterializacao.ServicoExposto.ServicoSoap.AdicionarCarro(ExemploMaterializacao.ServicoExposto.AdicionarCarroRequest request) {
            return base.Channel.AdicionarCarro(request);
        }
        
        public void AdicionarCarro(ExemploMaterializacao.ServicoExposto.CarroTO carroTO) {
            ExemploMaterializacao.ServicoExposto.AdicionarCarroRequest inValue = new ExemploMaterializacao.ServicoExposto.AdicionarCarroRequest();
            inValue.Body = new ExemploMaterializacao.ServicoExposto.AdicionarCarroRequestBody();
            inValue.Body.carroTO = carroTO;
            ExemploMaterializacao.ServicoExposto.AdicionarCarroResponse retVal = ((ExemploMaterializacao.ServicoExposto.ServicoSoap)(this)).AdicionarCarro(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ExemploMaterializacao.ServicoExposto.AdicionarCarroResponse> ExemploMaterializacao.ServicoExposto.ServicoSoap.AdicionarCarroAsync(ExemploMaterializacao.ServicoExposto.AdicionarCarroRequest request) {
            return base.Channel.AdicionarCarroAsync(request);
        }
        
        public System.Threading.Tasks.Task<ExemploMaterializacao.ServicoExposto.AdicionarCarroResponse> AdicionarCarroAsync(ExemploMaterializacao.ServicoExposto.CarroTO carroTO) {
            ExemploMaterializacao.ServicoExposto.AdicionarCarroRequest inValue = new ExemploMaterializacao.ServicoExposto.AdicionarCarroRequest();
            inValue.Body = new ExemploMaterializacao.ServicoExposto.AdicionarCarroRequestBody();
            inValue.Body.carroTO = carroTO;
            return ((ExemploMaterializacao.ServicoExposto.ServicoSoap)(this)).AdicionarCarroAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ExemploMaterializacao.ServicoExposto.AtualizarCarroResponse ExemploMaterializacao.ServicoExposto.ServicoSoap.AtualizarCarro(ExemploMaterializacao.ServicoExposto.AtualizarCarroRequest request) {
            return base.Channel.AtualizarCarro(request);
        }
        
        public void AtualizarCarro(ExemploMaterializacao.ServicoExposto.CarroTO carroTO) {
            ExemploMaterializacao.ServicoExposto.AtualizarCarroRequest inValue = new ExemploMaterializacao.ServicoExposto.AtualizarCarroRequest();
            inValue.Body = new ExemploMaterializacao.ServicoExposto.AtualizarCarroRequestBody();
            inValue.Body.carroTO = carroTO;
            ExemploMaterializacao.ServicoExposto.AtualizarCarroResponse retVal = ((ExemploMaterializacao.ServicoExposto.ServicoSoap)(this)).AtualizarCarro(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ExemploMaterializacao.ServicoExposto.AtualizarCarroResponse> ExemploMaterializacao.ServicoExposto.ServicoSoap.AtualizarCarroAsync(ExemploMaterializacao.ServicoExposto.AtualizarCarroRequest request) {
            return base.Channel.AtualizarCarroAsync(request);
        }
        
        public System.Threading.Tasks.Task<ExemploMaterializacao.ServicoExposto.AtualizarCarroResponse> AtualizarCarroAsync(ExemploMaterializacao.ServicoExposto.CarroTO carroTO) {
            ExemploMaterializacao.ServicoExposto.AtualizarCarroRequest inValue = new ExemploMaterializacao.ServicoExposto.AtualizarCarroRequest();
            inValue.Body = new ExemploMaterializacao.ServicoExposto.AtualizarCarroRequestBody();
            inValue.Body.carroTO = carroTO;
            return ((ExemploMaterializacao.ServicoExposto.ServicoSoap)(this)).AtualizarCarroAsync(inValue);
        }
        
        public void ExcluirCarro(int id) {
            base.Channel.ExcluirCarro(id);
        }
        
        public System.Threading.Tasks.Task ExcluirCarroAsync(int id) {
            return base.Channel.ExcluirCarroAsync(id);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ExemploMaterializacao.ServicoExposto.RegistrarUsuarioResponse ExemploMaterializacao.ServicoExposto.ServicoSoap.RegistrarUsuario(ExemploMaterializacao.ServicoExposto.RegistrarUsuarioRequest request) {
            return base.Channel.RegistrarUsuario(request);
        }
        
        public void RegistrarUsuario(ExemploMaterializacao.ServicoExposto.UsuarioTO usuarioTO) {
            ExemploMaterializacao.ServicoExposto.RegistrarUsuarioRequest inValue = new ExemploMaterializacao.ServicoExposto.RegistrarUsuarioRequest();
            inValue.Body = new ExemploMaterializacao.ServicoExposto.RegistrarUsuarioRequestBody();
            inValue.Body.usuarioTO = usuarioTO;
            ExemploMaterializacao.ServicoExposto.RegistrarUsuarioResponse retVal = ((ExemploMaterializacao.ServicoExposto.ServicoSoap)(this)).RegistrarUsuario(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ExemploMaterializacao.ServicoExposto.RegistrarUsuarioResponse> ExemploMaterializacao.ServicoExposto.ServicoSoap.RegistrarUsuarioAsync(ExemploMaterializacao.ServicoExposto.RegistrarUsuarioRequest request) {
            return base.Channel.RegistrarUsuarioAsync(request);
        }
        
        public System.Threading.Tasks.Task<ExemploMaterializacao.ServicoExposto.RegistrarUsuarioResponse> RegistrarUsuarioAsync(ExemploMaterializacao.ServicoExposto.UsuarioTO usuarioTO) {
            ExemploMaterializacao.ServicoExposto.RegistrarUsuarioRequest inValue = new ExemploMaterializacao.ServicoExposto.RegistrarUsuarioRequest();
            inValue.Body = new ExemploMaterializacao.ServicoExposto.RegistrarUsuarioRequestBody();
            inValue.Body.usuarioTO = usuarioTO;
            return ((ExemploMaterializacao.ServicoExposto.ServicoSoap)(this)).RegistrarUsuarioAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ExemploMaterializacao.ServicoExposto.LoginUsuarioResponse ExemploMaterializacao.ServicoExposto.ServicoSoap.LoginUsuario(ExemploMaterializacao.ServicoExposto.LoginUsuarioRequest request) {
            return base.Channel.LoginUsuario(request);
        }
        
        public ExemploMaterializacao.ServicoExposto.UsuarioTO LoginUsuario(string nomeUsuario, string senha) {
            ExemploMaterializacao.ServicoExposto.LoginUsuarioRequest inValue = new ExemploMaterializacao.ServicoExposto.LoginUsuarioRequest();
            inValue.Body = new ExemploMaterializacao.ServicoExposto.LoginUsuarioRequestBody();
            inValue.Body.nomeUsuario = nomeUsuario;
            inValue.Body.senha = senha;
            ExemploMaterializacao.ServicoExposto.LoginUsuarioResponse retVal = ((ExemploMaterializacao.ServicoExposto.ServicoSoap)(this)).LoginUsuario(inValue);
            return retVal.Body.LoginUsuarioResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ExemploMaterializacao.ServicoExposto.LoginUsuarioResponse> ExemploMaterializacao.ServicoExposto.ServicoSoap.LoginUsuarioAsync(ExemploMaterializacao.ServicoExposto.LoginUsuarioRequest request) {
            return base.Channel.LoginUsuarioAsync(request);
        }
        
        public System.Threading.Tasks.Task<ExemploMaterializacao.ServicoExposto.LoginUsuarioResponse> LoginUsuarioAsync(string nomeUsuario, string senha) {
            ExemploMaterializacao.ServicoExposto.LoginUsuarioRequest inValue = new ExemploMaterializacao.ServicoExposto.LoginUsuarioRequest();
            inValue.Body = new ExemploMaterializacao.ServicoExposto.LoginUsuarioRequestBody();
            inValue.Body.nomeUsuario = nomeUsuario;
            inValue.Body.senha = senha;
            return ((ExemploMaterializacao.ServicoExposto.ServicoSoap)(this)).LoginUsuarioAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ExemploMaterializacao.ServicoExposto.GetPerfilUsuarioResponse ExemploMaterializacao.ServicoExposto.ServicoSoap.GetPerfilUsuario(ExemploMaterializacao.ServicoExposto.GetPerfilUsuarioRequest request) {
            return base.Channel.GetPerfilUsuario(request);
        }
        
        public ExemploMaterializacao.ServicoExposto.UsuarioTO GetPerfilUsuario(string nomeUsuario) {
            ExemploMaterializacao.ServicoExposto.GetPerfilUsuarioRequest inValue = new ExemploMaterializacao.ServicoExposto.GetPerfilUsuarioRequest();
            inValue.Body = new ExemploMaterializacao.ServicoExposto.GetPerfilUsuarioRequestBody();
            inValue.Body.nomeUsuario = nomeUsuario;
            ExemploMaterializacao.ServicoExposto.GetPerfilUsuarioResponse retVal = ((ExemploMaterializacao.ServicoExposto.ServicoSoap)(this)).GetPerfilUsuario(inValue);
            return retVal.Body.GetPerfilUsuarioResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ExemploMaterializacao.ServicoExposto.GetPerfilUsuarioResponse> ExemploMaterializacao.ServicoExposto.ServicoSoap.GetPerfilUsuarioAsync(ExemploMaterializacao.ServicoExposto.GetPerfilUsuarioRequest request) {
            return base.Channel.GetPerfilUsuarioAsync(request);
        }
        
        public System.Threading.Tasks.Task<ExemploMaterializacao.ServicoExposto.GetPerfilUsuarioResponse> GetPerfilUsuarioAsync(string nomeUsuario) {
            ExemploMaterializacao.ServicoExposto.GetPerfilUsuarioRequest inValue = new ExemploMaterializacao.ServicoExposto.GetPerfilUsuarioRequest();
            inValue.Body = new ExemploMaterializacao.ServicoExposto.GetPerfilUsuarioRequestBody();
            inValue.Body.nomeUsuario = nomeUsuario;
            return ((ExemploMaterializacao.ServicoExposto.ServicoSoap)(this)).GetPerfilUsuarioAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ExemploMaterializacao.ServicoExposto.AtualizarPerfilUsuarioResponse ExemploMaterializacao.ServicoExposto.ServicoSoap.AtualizarPerfilUsuario(ExemploMaterializacao.ServicoExposto.AtualizarPerfilUsuarioRequest request) {
            return base.Channel.AtualizarPerfilUsuario(request);
        }
        
        public void AtualizarPerfilUsuario(ExemploMaterializacao.ServicoExposto.UsuarioTO usuarioTO) {
            ExemploMaterializacao.ServicoExposto.AtualizarPerfilUsuarioRequest inValue = new ExemploMaterializacao.ServicoExposto.AtualizarPerfilUsuarioRequest();
            inValue.Body = new ExemploMaterializacao.ServicoExposto.AtualizarPerfilUsuarioRequestBody();
            inValue.Body.usuarioTO = usuarioTO;
            ExemploMaterializacao.ServicoExposto.AtualizarPerfilUsuarioResponse retVal = ((ExemploMaterializacao.ServicoExposto.ServicoSoap)(this)).AtualizarPerfilUsuario(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ExemploMaterializacao.ServicoExposto.AtualizarPerfilUsuarioResponse> ExemploMaterializacao.ServicoExposto.ServicoSoap.AtualizarPerfilUsuarioAsync(ExemploMaterializacao.ServicoExposto.AtualizarPerfilUsuarioRequest request) {
            return base.Channel.AtualizarPerfilUsuarioAsync(request);
        }
        
        public System.Threading.Tasks.Task<ExemploMaterializacao.ServicoExposto.AtualizarPerfilUsuarioResponse> AtualizarPerfilUsuarioAsync(ExemploMaterializacao.ServicoExposto.UsuarioTO usuarioTO) {
            ExemploMaterializacao.ServicoExposto.AtualizarPerfilUsuarioRequest inValue = new ExemploMaterializacao.ServicoExposto.AtualizarPerfilUsuarioRequest();
            inValue.Body = new ExemploMaterializacao.ServicoExposto.AtualizarPerfilUsuarioRequestBody();
            inValue.Body.usuarioTO = usuarioTO;
            return ((ExemploMaterializacao.ServicoExposto.ServicoSoap)(this)).AtualizarPerfilUsuarioAsync(inValue);
        }
    }
}
